// Common medicines used as a fallback for sound-alike matching on the voice prescription screen.
export const COMMON_MEDICINES: string[] = [
  "Aceclofenac",
  "Acetaminophen",
  "Acetylcysteine",
  "Acyclovir",
  "Adapalene",
  "Albendazole",
  "Alendronate",
  "Alfuzosin",
  "Allopurinol",
  "Alprazolam",
  "Ambroxol",
  "Amiodarone",
  "Amitriptyline",
  "Amlodipine",
  "Amoxicillin",
  "Amoxicillin Clavulanate",
  "Ampicillin",
  "Antacid",
  "Apixaban",
  "Aripiprazole",
  "Aspirin",
  "Atenolol",
  "Atorvastatin",
  "Azithromycin",
  "Baclofen",
  "Becosules",
  "Benzoyl Peroxide",
  "Betahistine",
  "Betamethasone",
  "Biotin",
  "Bisacodyl",
  "Bisoprolol",
  "Bromhexine",
  "Budesonide",
  "Calamine",
  "Calcitriol",
  "Calcium Carbonate",
  "Carbamazepine",
  "Carbimazole",
  "Carboxymethylcellulose",
  "Carvedilol",
  "Cefixime",
  "Cefpodoxime",
  "Ceftriaxone",
  "Cefuroxime",
  "Cephalexin",
  "Cetirizine",
  "Chlorhexidine",
  "Chlorpheniramine",
  "Chlorthalidone",
  "Chlorzoxazone",
  "Cholecalciferol",
  "Cinnarizine",
  "Ciprofloxacin",
  "Ciprofloxacin Ear Drops",
  "Ciprofloxacin Eye Drops",
  "Clarithromycin",
  "Clindamycin",
  "Clindamycin Gel",
  "Clobetasol",
  "Clomiphene",
  "Clonazepam",
  "Clonidine",
  "Clopidogrel",
  "Clotrimazole",
  "Cloxacillin",
  "Colchicine",
  "Cotrimoxazole",
  "Dapagliflozin",
  "Deflazacort",
  "Deriphyllin",
  "Desloratadine",
  "Dexamethasone",
  "Dextromethorphan",
  "Diazepam",
  "Diclofenac",
  "Diclofenac Gel",
  "Digoxin",
  "Diltiazem",
  "Domperidone",
  "Domperidone Paracetamol",
  "Doxycycline",
  "Duloxetine",
  "Dutasteride",
  "Empagliflozin",
  "Enalapril",
  "Erythromycin",
  "Escitalopram",
  "Esomeprazole",
  "Etoricoxib",
  "Ezetimibe",
  "Famotidine",
  "Febuxostat",
  "Fenofibrate",
  "Ferrous Sulphate",
  "Fexofenadine",
  "Finasteride",
  "Fluconazole",
  "Flunarizine",
  "Fluoxetine",
  "Fluticasone",
  "Folic Acid",
  "Formoterol",
  "Furosemide",
  "Fusidic Acid",
  "Gabapentin",
  "Gliclazide",
  "Glimepiride",
  "Glipizide",
  "Griseofulvin",
  "Guaifenesin",
  "Haloperidol",
  "Hydrochlorothiazide",
  "Hydrocortisone",
  "Hydroxyzine",
  "Ibuprofen",
  "Indapamide",
  "Insulin Glargine",
  "Insulin Human",
  "Ipratropium",
  "Iron Sucrose",
  "Isosorbide Mononitrate",
  "Isotretinoin",
  "Itopride",
  "Itraconazole",
  "Ivermectin",
  "Ketoconazole",
  "Ketorolac",
  "Lactulose",
  "Lamotrigine",
  "Lansoprazole",
  "Latanoprost",
  "Letrozole",
  "Levetiracetam",
  "Levocetirizine",
  "Levofloxacin",
  "Levosalbutamol",
  "Levosulpiride",
  "Levothyroxine",
  "Lidocaine",
  "Linagliptin",
  "Linezolid",
  "Lisinopril",
  "Lithium",
  "Loperamide",
  "Loratadine",
  "Lorazepam",
  "Losartan",
  "Mebendazole",
  "Mefenamic Acid",
  "Mefenamic Tranexamic",
  "Melatonin",
  "Metformin",
  "Metformin Glimepiride",
  "Methimazole",
  "Methocarbamol",
  "Methylcobalamin",
  "Methylprednisolone",
  "Metoclopramide",
  "Metoprolol",
  "Metronidazole",
  "Minoxidil",
  "Mirabegron",
  "Mirtazapine",
  "Misoprostol",
  "Mometasone",
  "Montelukast",
  "Mouthwash",
  "Moxifloxacin",
  "Moxifloxacin Eye Drops",
  "Multivitamin",
  "Mupirocin",
  "Naproxen",
  "Nebivolol",
  "Nifedipine",
  "Nimesulide",
  "Nitrofurantoin",
  "Nitroglycerin",
  "Norethisterone",
  "Nortriptyline",
  "Ofloxacin",
  "Ofloxacin Ear Drops",
  "Ofloxacin Ornidazole",
  "Olanzapine",
  "Olmesartan",
  "Olopatadine",
  "Omeprazole",
  "Ondansetron",
  "Oral Rehydration Salts",
  "Ornidazole",
  "Oxcarbazepine",
  "Oxybutynin",
  "Oxymetazoline",
  "Pantoprazole",
  "Paracetamol",
  "Paroxetine",
  "Permethrin",
  "Pheniramine",
  "Phenobarbitone",
  "Phenytoin",
  "Pioglitazone",
  "Piroxicam",
  "Povidone Iodine",
  "Prasugrel",
  "Prednisolone",
  "Pregabalin",
  "Progesterone",
  "Propranolol",
  "Quetiapine",
  "Rabeprazole",
  "Racecadotril",
  "Ramipril",
  "Ranitidine",
  "Ranolazine",
  "Risperidone",
  "Rivaroxaban",
  "Rosuvastatin",
  "Salbutamol",
  "Saline Nasal Spray",
  "Sertraline",
  "Sildenafil",
  "Silodosin",
  "Silver Sulfadiazine",
  "Simethicone",
  "Simvastatin",
  "Sitagliptin",
  "Sodium Valproate",
  "Solifenacin",
  "Spironolactone",
  "Sucralfate",
  "Sumatriptan",
  "Tadalafil",
  "Tamsulosin",
  "Telmisartan",
  "Teneligliptin",
  "Terbinafine",
  "Theophylline",
  "Thiocolchicoside",
  "Ticagrelor",
  "Timolol",
  "Tinidazole",
  "Tizanidine",
  "Tobramycin Eye Drops",
  "Topiramate",
  "Torsemide",
  "Tramadol",
  "Tranexamic Acid",
  "Tretinoin",
  "Valacyclovir",
  "Valsartan",
  "Venlafaxine",
  "Verapamil",
  "Vildagliptin",
  "Vitamin B12",
  "Vitamin C",
  "Vitamin D3",
  "Warfarin",
  "Xylometazoline",
  "Zinc Oxide",
  "Zinc Sulphate",
  "Zolpidem",
];
