// Common medicines used as a fallback for sound-alike matching on the voice prescription screen.
export const COMMON_MEDICINES: string[] = [
  "Aceclofenac",
  "Acetaminophen",
  "Acetylcysteine",
  "Acyclovir",
  "Adapalene",
  "Albendazole",
  "Alendronate",
  "Alfuzosin",
  "Allopurinol",
  "Alprazolam",
  "Ambroxol",
  "Amiodarone",
  "Amitriptyline",
  "Amlodipine",
  "Amoxicillin",
  "Amoxicillin Clavulanate",
  "Ampicillin",
  "Antacid",
  "Apixaban",
  "Aripiprazole",
  "Aspirin",
  "Atenolol",
  "Atorvastatin",
  "Azithromycin",
  "Baclofen",
  "Becosules",
  "Benzoyl Peroxide",
  "Betahistine",
  "Betamethasone",
  "Biotin",
  "Bisacodyl",
  "Bisoprolol",
  "Bromhexine",
  "Budesonide",
  "Calamine",
  "Calcitriol",
  "Calcium Carbonate",
  "Carbamazepine",
  "Carbimazole",
  "Carboxymethylcellulose",
  "Carvedilol",
  "Cefixime",
  "Cefpodoxime",
  "Ceftriaxone",
  "Cefuroxime",
  "Cephalexin",
  "Cetirizine",
  "Chlorhexidine",
  "Chlorpheniramine",
  "Chlorthalidone",
  "Chlorzoxazone",
  "Cholecalciferol",
  "Cinnarizine",
  "Ciprofloxacin",
  "Ciprofloxacin Ear Drops",
  "Ciprofloxacin Eye Drops",
  "Clarithromycin",
  "Clindamycin",
  "Clindamycin Gel",
  "Clobetasol",
  "Clomiphene",
  "Clonazepam",
  "Clonidine",
  "Clopidogrel",
  "Clotrimazole",
  "Cloxacillin",
  "Colchicine",
  "Cotrimoxazole",
  "Dapagliflozin",
  "Deflazacort",
  "Deriphyllin",
  "Desloratadine",
  "Dexamethasone",
  "Dextromethorphan",
  "Diazepam",
  "Diclofenac",
  "Diclofenac Gel",
  "Digoxin",
  "Diltiazem",
  "Domperidone",
  "Domperidone Paracetamol",
  "Doxycycline",
  "Duloxetine",
  "Dutasteride",
  "Empagliflozin",
  "Enalapril",
  "Erythromycin",
  "Escitalopram",
  "Esomeprazole",
  "Etoricoxib",
  "Ezetimibe",
  "Famotidine",
  "Febuxostat",
  "Fenofibrate",
  "Ferrous Sulphate",
  "Fexofenadine",
  "Finasteride",
  "Fluconazole",
  "Flunarizine",
  "Fluoxetine",
  "Fluticasone",
  "Folic Acid",
  "Formoterol",
  "Furosemide",
  "Fusidic Acid",
  "Gabapentin",
  "Gliclazide",
  "Glimepiride",
  "Glipizide",
  "Griseofulvin",
  "Guaifenesin",
  "Haloperidol",
  "Hydrochlorothiazide",
  "Hydrocortisone",
  "Hydroxyzine",
  "Ibuprofen",
  "Indapamide",
  "Insulin Glargine",
  "Insulin Human",
  "Ipratropium",
  "Iron Sucrose",
  "Isosorbide Mononitrate",
  "Isotretinoin",
  "Itopride",
  "Itraconazole",
  "Ivermectin",
  "Ketoconazole",
  "Ketorolac",
  "Lactulose",
  "Lamotrigine",
  "Lansoprazole",
  "Latanoprost",
  "Letrozole",
  "Levetiracetam",
  "Levocetirizine",
  "Levofloxacin",
  "Levosalbutamol",
  "Levosulpiride",
  "Levothyroxine",
  "Lidocaine",
  "Linagliptin",
  "Linezolid",
  "Lisinopril",
  "Lithium",
  "Loperamide",
  "Loratadine",
  "Lorazepam",
  "Losartan",
  "Mebendazole",
  "Mefenamic Acid",
  "Mefenamic Tranexamic",
  "Melatonin",
  "Metformin",
  "Metformin Glimepiride",
  "Methimazole",
  "Methocarbamol",
  "Methylcobalamin",
  "Methylprednisolone",
  "Metoclopramide",
  "Metoprolol",
  "Metronidazole",
  "Minoxidil",
  "Mirabegron",
  "Mirtazapine",
  "Misoprostol",
  "Mometasone",
  "Montelukast",
  "Mouthwash",
  "Moxifloxacin",
  "Moxifloxacin Eye Drops",
  "Multivitamin",
  "Mupirocin",
  "Naproxen",
  "Nebivolol",
  "Nifedipine",
  "Nimesulide",
  "Nitrofurantoin",
  "Nitroglycerin",
  "Norethisterone",
  "Nortriptyline",
  "Ofloxacin",
  "Ofloxacin Ear Drops",
  "Ofloxacin Ornidazole",
  "Olanzapine",
  "Olmesartan",
  "Olopatadine",
  "Omeprazole",
  "Ondansetron",
  "Oral Rehydration Salts",
  "Ornidazole",
  "Oxcarbazepine",
  "Oxybutynin",
  "Oxymetazoline",
  "Pantoprazole",
  "Paracetamol",
  "Paroxetine",
  "Permethrin",
  "Pheniramine",
  "Phenobarbitone",
  "Phenytoin",
  "Pioglitazone",
  "Piroxicam",
  "Povidone Iodine",
  "Prasugrel",
  "Prednisolone",
  "Pregabalin",
  "Progesterone",
  "Propranolol",
  "Quetiapine",
  "Rabeprazole",
  "Racecadotril",
  "Ramipril",
  "Ranitidine",
  "Ranolazine",
  "Risperidone",
  "Rivaroxaban",
  "Rosuvastatin",
  "Salbutamol",
  "Saline Nasal Spray",
  "Sertraline",
  "Sildenafil",
  "Silodosin",
  "Silver Sulfadiazine",
  "Simethicone",
  "Simvastatin",
  "Sitagliptin",
  "Sodium Valproate",
  "Solifenacin",
  "Spironolactone",
  "Sucralfate",
  "Sumatriptan",
  "Tadalafil",
  "Tamsulosin",
  "Telmisartan",
  "Teneligliptin",
  "Terbinafine",
  "Theophylline",
  "Thiocolchicoside",
  "Ticagrelor",
  "Timolol",
  "Tinidazole",
  "Tizanidine",
  "Tobramycin Eye Drops",
  "Topiramate",
  "Torsemide",
  "Tramadol",
  "Tranexamic Acid",
  "Tretinoin",
  "Valacyclovir",
  "Valsartan",
  "Venlafaxine",
  "Verapamil",
  "Vildagliptin",
  "Vitamin B12",
  "Vitamin C",
  "Vitamin D3",
  "Warfarin",
  "Xylometazoline",
  "Zinc Oxide",
  "Zinc Sulphate",
  "Zolpidem",
  "Abacavir",
  "Abiraterone",
  "Acarbose",
  "Acebrophylline",
  "Acetazolamide",
  "Aciclovir",
  "Acitretin",
  "Activated Charcoal",
  "Albendazole Ivermectin",
  "Albuterol",
  "Alfacalcidol",
  "Aliskiren",
  "Almotriptan",
  "Alogliptin",
  "Alosetron",
  "Alpha Lipoic Acid",
  "Amantadine",
  "Amikacin",
  "Amiloride",
  "Aminophylline",
  "Amisulpride",
  "Amlodipine Atenolol",
  "Amlodipine Telmisartan",
  "Amoxapine",
  "Amphotericin B",
  "Anastrozole",
  "Apremilast",
  "Armodafinil",
  "Artemether",
  "Artesunate",
  "Artificial Tears",
  "Asenapine",
  "Atomoxetine",
  "Atracurium",
  "Atropine",
  "Azathioprine",
  "Azelastine",
  "Aztreonam",
  "Bacillus Clausii",
  "Beclomethasone",
  "Bempedoic Acid",
  "Benazepril",
  "Benfotiamine",
  "Benzathine Penicillin",
  "Benzhexol",
  "Benzydamine",
  "Betaxolol",
  "Bethanechol",
  "Bicalutamide",
  "Bimatoprost",
  "Bleomycin",
  "Bosentan",
  "Brimonidine",
  "Brinzolamide",
  "Brinzolamide Timolol",
  "Brivaracetam",
  "Bromocriptine",
  "Bumetanide",
  "Bupivacaine",
  "Buprenorphine",
  "Bupropion",
  "Buspirone",
  "Cabergoline",
  "Calcium Citrate",
  "Calcium Gluconate",
  "Calcium Vitamin D3",
  "Canagliflozin",
  "Candesartan",
  "Capecitabine",
  "Captopril",
  "Carbidopa",
  "Carbocisteine",
  "Carboplatin",
  "Cefaclor",
  "Cefadroxil",
  "Cefdinir",
  "Cefepime",
  "Cefoperazone",
  "Cefotaxime",
  "Cefprozil",
  "Ceftazidime",
  "Celecoxib",
  "Cetirizine Phenylephrine",
  "Chloramphenicol",
  "Chloramphenicol Ear Drops",
  "Chlordiazepoxide",
  "Chloroquine",
  "Chlorpromazine",
  "Chlorpropamide",
  "Ciclopirox",
  "Cilostazol",
  "Cimetidine",
  "Cinitapride",
  "Citalopram",
  "Clobazam",
  "Clomipramine",
  "Clotrimazole Beclomethasone",
  "Clotrimazole Ear Drops",
  "Clozapine",
  "Codeine",
  "Coenzyme Q10",
  "Colistin",
  "Cough Syrup",
  "Cyclophosphamide",
  "Cyclosporine",
  "Cyproheptadine",
  "Cyproterone",
  "Dabigatran",
  "Daclatasvir",
  "Dalteparin",
  "Dapagliflozin Metformin",
  "Dapoxetine",
  "Dapsone",
  "Daptomycin",
  "Darifenacin",
  "Deferasirox",
  "Denosumab",
  "Desmopressin",
  "Desvenlafaxine",
  "Dexlansoprazole",
  "Dexmedetomidine",
  "Dexpanthenol",
  "Dextrose",
  "Diclofenac Paracetamol",
  "Dicyclomine",
  "Didanosine",
  "Dienogest",
  "Diethylcarbamazine",
  "Dihydroergotamine",
  "Diloxanide",
  "Dimenhydrinate",
  "Diphenhydramine",
  "Dipyridamole",
  "Disulfiram",
  "Dobutamine",
  "Docetaxel",
  "Dolutegravir",
  "Donepezil",
  "Dopamine",
  "Dorzolamide",
  "Dorzolamide Timolol",
  "Doxazosin",
  "Doxofylline",
  "Doxylamine",
  "Drotaverine",
  "Dydrogesterone",
  "Efavirenz",
  "Eletriptan",
  "Emtricitabine",
  "Enalapril Hydrochlorothiazide",
  "Enoxaparin",
  "Entacapone",
  "Entecavir",
  "Ephedrine",
  "Epinephrine",
  "Eplerenone",
  "Eprosartan",
  "Ergocalciferol",
  "Erlotinib",
  "Ertapenem",
  "Escitalopram Clonazepam",
  "Eszopiclone",
  "Ethambutol",
  "Ethinylestradiol",
  "Ethionamide",
  "Etofylline",
  "Everolimus",
  "Exemestane",
  "Famciclovir",
  "Felodipine",
  "Fenofibrate Atorvastatin",
  "Fentanyl",
  "Ferric Carboxymaltose",
  "Ferrous Ascorbate",
  "Ferrous Fumarate",
  "Fesoterodine",
  "Flavoxate",
  "Flecainide",
  "Fludrocortisone",
  "Fluorouracil",
  "Flupentixol",
  "Fluvoxamine",
  "Fondaparinux",
  "Fosfomycin",
  "Fosinopril",
  "Framycetin",
  "Galantamine",
  "Ganciclovir",
  "Gatifloxacin",
  "Gefitinib",
  "Gemcitabine",
  "Gemfibrozil",
  "Gentamicin",
  "Gentamicin Eye Drops",
  "Glibenclamide",
  "Gliclazide Metformin",
  "Glimepiride Metformin",
  "Glucosamine",
  "Glycerin Suppository",
  "Glyceryl Trinitrate",
  "Glycopyrrolate",
  "Granisetron",
  "Guanfacine",
  "Heparin",
  "Hyaluronic Acid",
  "Hydralazine",
  "Hydroxychloroquine",
  "Hydroxyurea",
  "Hyoscine",
  "Hyoscine Butylbromide",
  "Ibandronate",
  "Imatinib",
  "Imipenem",
  "Imipramine",
  "Indomethacin",
  "Insulin Aspart",
  "Insulin Degludec",
  "Insulin Isophane",
  "Insulin Lispro",
  "Interferon",
  "Irbesartan",
  "Irinotecan",
  "Iron Folic Acid",
  "Isoniazid",
  "Isosorbide Dinitrate",
  "Isoxsuprine",
  "Ispaghula Husk",
  "Ivabradine",
  "Kanamycin",
  "Ketamine",
  "Ketoprofen",
  "Ketotifen",
  "L Arginine",
  "Labetalol",
  "Lacidipine",
  "Lacosamide",
  "Lactobacillus",
  "Lactulose Syrup",
  "Lamivudine",
  "Lanthanum",
  "Leflunomide",
  "Lercanidipine",
  "Leucovorin",
  "Levamisole",
  "Levocarnitine",
  "Levodopa",
  "Levonorgestrel",
  "Levosulpiride Pantoprazole",
  "Lignocaine",
  "Linagliptin Metformin",
  "Liraglutide",
  "Lisinopril Hydrochlorothiazide",
  "Lithium Carbonate",
  "Lomustine",
  "Loperamide Simethicone",
  "Lopinavir",
  "Lornoxicam",
  "Losartan Hydrochlorothiazide",
  "Lovastatin",
  "Loxapine",
  "Lurasidone",
  "Lycopene",
  "Magaldrate",
  "Magnesium Citrate",
  "Magnesium Hydroxide",
  "Magnesium Sulphate",
  "Mannitol",
  "Maprotiline",
  "Mebeverine",
  "Mecobalamin",
  "Medroxyprogesterone",
  "Mefloquine",
  "Megestrol",
  "Meloxicam",
  "Melphalan",
  "Memantine",
  "Meropenem",
  "Mesalamine",
  "Mesna",
  "Metaxalone",
  "Methadone",
  "Methotrexate",
  "Methyldopa",
  "Methylergometrine",
  "Methylphenidate",
  "Metolazone",
  "Metoprolol Amlodipine",
  "Metronidazole Norfloxacin",
  "Mianserin",
  "Miconazole",
  "Midazolam",
  "Midodrine",
  "Mifepristone",
  "Miglitol",
  "Milnacipran",
  "Minocycline",
  "Mitomycin",
  "Modafinil",
  "Moxifloxacin Dexamethasone",
  "Moxonidine",
  "Multivitamin Multimineral",
  "Mycophenolate",
  "Nabumetone",
  "Nadolol",
  "Naftidrofuryl",
  "Nalidixic Acid",
  "Naloxone",
  "Naltrexone",
  "Naratriptan",
  "Nateglinide",
  "Nebivolol Hydrochlorothiazide",
  "Neomycin",
  "Neostigmine",
  "Netilmicin",
  "Nevirapine",
  "Niacin",
  "Nicorandil",
  "Nicotine",
  "Nimodipine",
  "Nitazoxanide",
  "Nitrazepam",
  "Nitroglycerine",
  "Norfloxacin",
  "Nystatin",
  "Octreotide",
  "Ofloxacin Dexamethasone",
  "Olanzapine Fluoxetine",
  "Olmesartan Amlodipine",
  "Olmesartan Hydrochlorothiazide",
  "Omega 3 Fatty Acids",
  "Omeprazole Domperidone",
  "Omeprazole Sodium Bicarbonate",
  "Orlistat",
  "Orphenadrine",
  "Oseltamivir",
  "Oxaliplatin",
  "Oxetacaine",
  "Oxytocin",
  "Paliperidone",
  "Pamidronate",
  "Pancreatin",
  "Pancuronium",
  "Pantoprazole Domperidone",
  "Papaverine",
  "Paracetamol Chlorzoxazone",
  "Paracetamol Tramadol",
  "Paroxetine Clonazepam",
  "Pazopanib",
  "Penicillin V",
  "Pentoxifylline",
  "Peppermint Oil",
  "Perindopril",
  "Perphenazine",
  "Phenobarbital",
  "Phenylephrine",
  "Phytomenadione",
  "Pilocarpine",
  "Pimozide",
  "Pinaverium",
  "Pindolol",
  "Pioglitazone Metformin",
  "Piperacillin Tazobactam",
  "Piracetam",
  "Pirfenidone",
  "Pitavastatin",
  "Polymyxin B",
  "Posaconazole",
  "Potassium Chloride",
  "Potassium Citrate",
  "Povidone Iodine Gargle",
  "Pramipexole",
  "Pravastatin",
  "Praziquantel",
  "Prazosin",
  "Prebiotic",
  "Prednisolone Eye Drops",
  "Prednisone",
  "Primaquine",
  "Primidone",
  "Probenecid",
  "Probiotic",
  "Procarbazine",
  "Prochlorperazine",
  "Promethazine",
  "Propafenone",
  "Propylthiouracil",
  "Psyllium",
  "Pyrazinamide",
  "Pyridostigmine",
  "Pyridoxine",
  "Quinapril",
  "Quinine",
  "Rabeprazole Domperidone",
  "Raloxifene",
  "Raltegravir",
  "Ramipril Hydrochlorothiazide",
  "Rasagiline",
  "Repaglinide",
  "Ribavirin",
  "Rifabutin",
  "Rifampicin",
  "Rifaximin",
  "Riluzole",
  "Risedronate",
  "Ritonavir",
  "Rivastigmine",
  "Rizatriptan",
  "Ropinirole",
  "Ropivacaine",
  "Roxithromycin",
  "Rufinamide",
  "Saxagliptin",
  "Secnidazole",
  "Selegiline",
  "Semaglutide",
  "Senna",
  "Sertaconazole",
  "Sevelamer",
  "Sevoflurane",
  "Sibutramine",
  "Sildenafil Dapoxetine",
  "Sirolimus",
  "Sodium Bicarbonate",
  "Sodium Chloride",
  "Sodium Fusidate",
  "Sodium Hyaluronate",
  "Sofosbuvir",
  "Sorafenib",
  "Sotalol",
  "Spiramycin",
  "Stavudine",
  "Streptomycin",
  "Strontium",
  "Sucralfate Oxetacaine",
  "Sulfasalazine",
  "Sulpiride",
  "Sultamicillin",
  "Tacrolimus",
  "Tadalafil Dapoxetine",
  "Tamoxifen",
  "Tapentadol",
  "Teicoplanin",
  "Telmisartan Amlodipine",
  "Telmisartan Hydrochlorothiazide",
  "Temozolomide",
  "Tenofovir",
  "Terazosin",
  "Terbutaline",
  "Teriflunomide",
  "Terlipressin",
  "Testosterone",
  "Tetracycline",
  "Thiamine",
  "Thioridazine",
  "Tiagabine",
  "Tianeptine",
  "Ticlopidine",
  "Tigecycline",
  "Tiotropium",
  "Tirofiban",
  "Tobramycin",
  "Tolterodine",
  "Tolvaptan",
  "Trandolapril",
  "Trazodone",
  "Triamcinolone",
  "Triamterene",
  "Trifluoperazine",
  "Trihexyphenidyl",
  "Trimebutine",
  "Trimetazidine",
  "Trimethoprim",
  "Triptorelin",
  "Trospium",
  "Ulipristal",
  "Urea",
  "Ursodeoxycholic Acid",
  "Valganciclovir",
  "Valproic Acid",
  "Vancomycin",
  "Vardenafil",
  "Varenicline",
  "Vasopressin",
  "Vecuronium",
  "Vigabatrin",
  "Vilazodone",
  "Vinblastine",
  "Vincristine",
  "Vitamin A",
  "Vitamin B1",
  "Vitamin B6",
  "Vitamin E",
  "Vitamin K",
  "Voglibose",
  "Voriconazole",
  "Vortioxetine",
  "Wax Softener",
  "Zidovudine",
  "Zinc Acetate",
  "Zinc Gluconate",
  "Ziprasidone",
  "Zoledronic Acid",
  "Zolmitriptan",
  "Zonisamide",
  "Zopiclone",
  "Cough Tonic",
  "Iron Tonic",
  "Multivitamin Tonic",
  "Liver Tonic",
  "Digestive Tonic",
  "Appetite Tonic",
  "Calcium Syrup",
  "Antacid Syrup",
  "Zinc Syrup",
  "Paracetamol Syrup",
  "Ibuprofen Syrup",
  "Ointment",
  "Antiseptic Cream",
  "Eye Ointment",
  "Ear Drops",
  "Nasal Drops",
  "Gargle",
  "Mouth Wash",
  "Oral Rehydration Solution",
];
